services:
    ollama:
       container_name: ollama
       image: ollama/ollama:latest
       ports:
         - 11434:11434
       volumes:
         - /ollama:/root/.ollama
       pull_policy: always
       restart: always